[book]
authors = ["Denis Gukov"]
language = "en"
multilingual = false
src = "src"
title = "Semaphore Docs"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css", "theme/search.css"]
additional-js = ["theme/tabs.js"]
google-analytics = "G-SXDFVHLVBM"
edit-url-template = "https://github.com/semaphoreui/semaphore-docs/edit/main/{path}"
site-url = "https://semaphoreui.com"

[output.html.search]
enable = true
limit-results = 10